//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personelwcf.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonel
    {
        public int PersonelId { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<int> DepartmanId { get; set; }
        public Nullable<decimal> Maas { get; set; }
        public Nullable<int> ilId { get; set; }
        public Nullable<int> ilceId { get; set; }
        public string pResim { get; set; }
        public byte[] ResimImage { get; set; }
    
        public virtual Departman Departman { get; set; }
        public virtual ilceler ilceler { get; set; }
        public virtual iller iller { get; set; }
    }
}
